# Generated by Django 6.0.4 on 2026-04-09 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='home_number',
            new_name='building_number',
        ),
        migrations.AddField(
            model_name='kitten',
            name='age_months',
            field=models.PositiveIntegerField(default=67),
        ),
        migrations.AddField(
            model_name='kitten',
            name='breed',
            field=models.CharField(default='Tang Tang', max_length=67),
        ),
        migrations.AddField(
            model_name='kitten',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='kitten',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_kittens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(default='Almaty', max_length=67),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.TextField(max_length=67),
        ),
        migrations.AlterField(
            model_name='kitten',
            name='name',
            field=models.CharField(max_length=67),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tag', models.CharField(choices=[('REQ', 'Request'), ('QUE', 'Question'), ('ADV', 'Advice'), ('NON', 'None')], default='NON', max_length=3)),
                ('kitten', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_messages', to='api.kitten')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
