# Generated by Django 6.0.4 on 2026-04-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_home_number_address_building_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitten',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
