# Generated by Django 6.0.4 on 2026-04-13 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_kitten_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitten',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kittens', to='api.address'),
        ),
    ]
