# Generated by Django 6.0.4 on 2026-04-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_adoptionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitten',
            name='is_adopted',
            field=models.BooleanField(default=False),
        ),
    ]
